# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abcSingleWidget.ui'
#
# Created: Fri Apr 12 18:42:43 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_abcS_form(object):
    def setupUi(self, abcS_form):
        abcS_form.setObjectName(_fromUtf8("abcS_form"))
        abcS_form.resize(428, 376)
        self.gridLayout = QtGui.QGridLayout(abcS_form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.abcFrm = QtGui.QFrame(abcS_form)
        self.abcFrm.setMinimumSize(QtCore.QSize(410, 300))
        self.abcFrm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.abcFrm.setFrameShape(QtGui.QFrame.Panel)
        self.abcFrm.setFrameShadow(QtGui.QFrame.Raised)
        self.abcFrm.setObjectName(_fromUtf8("abcFrm"))
        self.verticalLayout = QtGui.QVBoxLayout(self.abcFrm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.abcFrm)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter = QtGui.QSplitter(self.abcFrm)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_2 = QtGui.QLabel(self.splitter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.st_line = QtGui.QLineEdit(self.splitter)
        self.st_line.setMinimumSize(QtCore.QSize(0, 25))
        self.st_line.setObjectName(_fromUtf8("st_line"))
        self.horizontalLayout_4.addWidget(self.splitter)
        self.splitter_2 = QtGui.QSplitter(self.abcFrm)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_3 = QtGui.QLabel(self.splitter_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.end_line = QtGui.QLineEdit(self.splitter_2)
        self.end_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.end_line.setObjectName(_fromUtf8("end_line"))
        self.horizontalLayout_4.addWidget(self.splitter_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pth_line = QtGui.QLineEdit(self.abcFrm)
        self.pth_line.setObjectName(_fromUtf8("pth_line"))
        self.horizontalLayout.addWidget(self.pth_line)
        self.cc_pth_bt = QtGui.QPushButton(self.abcFrm)
        self.cc_pth_bt.setIconSize(QtCore.QSize(16, 16))
        self.cc_pth_bt.setObjectName(_fromUtf8("cc_pth_bt"))
        self.horizontalLayout.addWidget(self.cc_pth_bt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.rc_bt = QtGui.QPushButton(self.abcFrm)
        self.rc_bt.setObjectName(_fromUtf8("rc_bt"))
        self.horizontalLayout_5.addWidget(self.rc_bt)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.ex_cc_bt = QtGui.QPushButton(self.abcFrm)
        self.ex_cc_bt.setObjectName(_fromUtf8("ex_cc_bt"))
        self.horizontalLayout_5.addWidget(self.ex_cc_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_3 = QtGui.QFrame(self.abcFrm)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.line_2 = QtGui.QFrame(self.abcFrm)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtGui.QLabel(self.abcFrm)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.sel_cc_bt = QtGui.QPushButton(self.abcFrm)
        self.sel_cc_bt.setObjectName(_fromUtf8("sel_cc_bt"))
        self.verticalLayout.addWidget(self.sel_cc_bt)
        self.im_lst_tx = QtGui.QTextEdit(self.abcFrm)
        self.im_lst_tx.setMaximumSize(QtCore.QSize(16777215, 50))
        self.im_lst_tx.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.im_lst_tx.setReadOnly(False)
        self.im_lst_tx.setObjectName(_fromUtf8("im_lst_tx"))
        self.verticalLayout.addWidget(self.im_lst_tx)
        self.line = QtGui.QFrame(self.abcFrm)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.holdBx = QtGui.QGroupBox(self.abcFrm)
        self.holdBx.setMinimumSize(QtCore.QSize(250, 40))
        self.holdBx.setObjectName(_fromUtf8("holdBx"))
        self.ref_rb = QtGui.QRadioButton(self.holdBx)
        self.ref_rb.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.ref_rb.setChecked(True)
        self.ref_rb.setObjectName(_fromUtf8("ref_rb"))
        self.mod_grp = QtGui.QButtonGroup(abcS_form)
        self.mod_grp.setObjectName(_fromUtf8("mod_grp"))
        self.mod_grp.addButton(self.ref_rb)
        self.im_rb = QtGui.QRadioButton(self.holdBx)
        self.im_rb.setGeometry(QtCore.QRect(110, 20, 89, 16))
        self.im_rb.setChecked(False)
        self.im_rb.setObjectName(_fromUtf8("im_rb"))
        self.mod_grp.addButton(self.im_rb)
        self.horizontalLayout_3.addWidget(self.holdBx)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.im_cc_bt = QtGui.QPushButton(self.abcFrm)
        self.im_cc_bt.setObjectName(_fromUtf8("im_cc_bt"))
        self.horizontalLayout_3.addWidget(self.im_cc_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.abcFrm, 0, 0, 1, 1)

        self.retranslateUi(abcS_form)
        QtCore.QMetaObject.connectSlotsByName(abcS_form)

    def retranslateUi(self, abcS_form):
        abcS_form.setWindowTitle(_translate("abcS_form", "Form", None))
        self.label.setText(_translate("abcS_form", "输出缓存：选择要输出缓存的模型", None))
        self.label_2.setText(_translate("abcS_form", "start frame", None))
        self.label_3.setText(_translate("abcS_form", "end   frame", None))
        self.cc_pth_bt.setText(_translate("abcS_form", "path", None))
        self.rc_bt.setText(_translate("abcS_form", "只记录缓存物体", None))
        self.ex_cc_bt.setText(_translate("abcS_form", "Export Cache & record file", None))
        self.label_4.setText(_translate("abcS_form", "导入缓存", None))
        self.sel_cc_bt.setText(_translate("abcS_form", "选择：缓存 及记录 物体的文件", None))
        self.holdBx.setTitle(_translate("abcS_form", "读取缓存物体保持", None))
        self.ref_rb.setText(_translate("abcS_form", "Reference", None))
        self.im_rb.setText(_translate("abcS_form", "Import", None))
        self.im_cc_bt.setText(_translate("abcS_form", "importCache", None))

